import type { GastroPreset } from "./types";

const bodegonCategories = [
  { id: "cantina", name: "Entradas & Tortillas", description: "Tortillas babé al momento, empanadas y picadas de cantina." },
  { id: "milanesas", name: "Milanesas Gigantes", description: "Cortes de ternera bien golpeados, gratinados y para compartir." },
  { id: "pastas", name: "Pastas al Huevo", description: "Pastas frescas amasadas al mediodía con estofados de cocción lenta." },
  { id: "bodega", name: "Vermut & Sifón", description: "Aperitivos tirados, soda de sifón pesado y vinos de la casa." },
  { id: "postres", name: "Postres de Cantina", description: "Flanes de 12 yemas con dulce de leche y budines mixtos." },
];

const guarniciones = [
  { id: "papas-fritas", name: "Papas fritas a caballo", priceDelta: 0 },
  { id: "pure-mixto", name: "Puré mixto con manteca", priceDelta: 0 },
  { id: "ensalada-rusa", name: "Ensalada rusa de la casa", priceDelta: 0 },
];

const bodegonProducts = [
  {
    id: "mila-napolitana-bodegon",
    categoryId: "milanesas",
    name: "Milanesa Napolitana para Dos",
    description: "Corte de ternera empanado, salsa de tomate casera, jamón cocido y montaña de mozzarella gratinada.",
    price: 24800,
    image: "https://images.unsplash.com/photo-1606755456206-b25206cde27e?auto=format&fit=crop&w=1600&q=85",
    tags: ["Para compartir", "Best Seller"],
    prepTime: "22 min",
    isFeatured: true,
  },
  {
    id: "tortilla-espanola",
    categoryId: "cantina",
    name: "Tortilla de Papas Babé",
    description: "Papas confitadas lentamente con cebolla, huevos de campo y centro bien líquido y cremoso.",
    price: 12600,
    image: "https://images.unsplash.com/photo-1604908554027-1d3a6c0d6f5a?auto=format&fit=crop&w=1600&q=85",
    tags: ["Punto babé"],
    prepTime: "14 min",
    isFeatured: true,
  },
  {
    id: "tallarines-estofado-bodegon",
    categoryId: "pastas",
    name: "Tallarines Caseros con Estofado de Osobuco",
    description: "Fideos al huevo al dente bañados en salsa de tomate cocida durante 6 horas con osobuco tierno.",
    price: 18200,
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1600&q=85",
    tags: ["Receta de la abuela"],
    prepTime: "18 min",
  },
  {
    id: "vermut-sifon-bodegon",
    categoryId: "bodega",
    name: "Vermut de Grifo con Sifón de Soda",
    description: "Vermut rosso servido en vaso pingüino con rodaja de naranja, aceituna verde y sifón de vidrio.",
    price: 5800,
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1600&q=85",
    tags: ["El aperitivo"],
    prepTime: "4 min",
  },
  {
    id: "flan-casero-bodegon",
    categoryId: "postres",
    name: "Flan Casero Mixto (Dulce & Crema)",
    description: "Flan de huevos de campo con agujeritos, servido con dulce de leche repostero y crema montada.",
    price: 6400,
    image: "https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?auto=format&fit=crop&w=1600&q=85",
    tags: ["Clásico porteño"],
    prepTime: "4 min",
  },
];

export const bodegonPreset: GastroPreset = {
  id: "bodegon",
  label: "Bodegón Porteño & Cantina",

  theme: {
    mode: "hybrid",
    accent: "#C7923E",
    accentStrong: "#E2AC55",
    accentContrast: "#14100D",

    colors: {
      light: {
        bg: "#F9F6F0",
        bgElevated: "#FFFFFF",
        surface: "#FFFFFF",
        surfaceElevated: "#EBE3D7",
        surfaceInverse: "#18130F",
        text: "#1E1712",
        textMuted: "#605347",
        textSubtle: "#827467",
        accent: "#A67222",
        accentStrong: "#7D5210",
        accentContrast: "#FFFFFF",
        accentSoft: "rgba(166, 114, 34, 0.12)",
        accentFaint: "rgba(166, 114, 34, 0.05)",
        accentBorder: "rgba(166, 114, 34, 0.35)",
        border: "rgba(30, 23, 18, 0.11)",
        borderStrong: "rgba(30, 23, 18, 0.22)",
        overlay: "rgba(249, 246, 240, 0.92)",
        control: "rgba(30, 23, 18, 0.05)",
        controlHover: "rgba(30, 23, 18, 0.09)",
        success: "#059669",
        warning: "#B45309",
        danger: "#DC2626",
      },
      hybrid: {
        bg: "#14100D",
        bgElevated: "#1A1511",
        surface: "#211A14",
        surfaceElevated: "#2C231B",
        surfaceInverse: "#F7F0E6",
        text: "#F7F0E6",
        textMuted: "#C6B7A4",
        textSubtle: "#8F8170",
        accent: "#C7923E",
        accentStrong: "#E2AC55",
        accentContrast: "#14100D",
        accentSoft: "rgba(199, 146, 62, 0.16)",
        accentFaint: "rgba(199, 146, 62, 0.08)",
        accentBorder: "rgba(199, 146, 62, 0.38)",
        border: "rgba(247, 240, 230, 0.11)",
        borderStrong: "rgba(247, 240, 230, 0.22)",
        overlay: "rgba(20, 16, 13, 0.92)",
        control: "rgba(247, 240, 230, 0.05)",
        controlHover: "rgba(247, 240, 230, 0.09)",
        success: "#34D399",
        warning: "#F59E0B",
        danger: "#F87171",
      },
      dark: {
        bg: "#120E0B",
        bgElevated: "#18130F",
        surface: "#1E1813",
        surfaceElevated: "#28201A",
        surfaceInverse: "#F7F0E6",
        text: "#F7F0E6",
        textMuted: "#C6B7A4",
        textSubtle: "#8F8170",
        accent: "#C7923E",
        accentStrong: "#E2AC55",
        accentContrast: "#14100D",
        accentSoft: "rgba(199, 146, 62, 0.16)",
        accentFaint: "rgba(199, 146, 62, 0.08)",
        accentBorder: "rgba(199, 146, 62, 0.38)",
        border: "rgba(247, 240, 230, 0.11)",
        borderStrong: "rgba(247, 240, 230, 0.22)",
        overlay: "rgba(18, 14, 11, 0.92)",
        control: "rgba(247, 240, 230, 0.05)",
        controlHover: "rgba(247, 240, 230, 0.09)",
        success: "#34D399",
        warning: "#F59E0B",
        danger: "#F87171",
      },
    },

    typography: {
      display: "Georgia, 'Times New Roman', serif",
      body: "Inter, Arial, sans-serif",
      ui: "Inter, Arial, sans-serif",
      mono: "monospace",
    },
  },

  visual: {
    navbar: "editorial",
    hero: "editorial",
    heroStyle: {
      variant: "editorial",
      imageTreatment: "film",
      overlay: "editorial",
      composition: "standard",
      ctaShape: "circle",
      grain: true,
      parallax: true,
      intensity: 0.92,
    },
    menu: "catalog",
    productCard: "photo",
    contact: "split",
    cta: "immersive",
    footer: "editorial",
    story: {
      variant: "cantina",
      layout: "lookbook",
      imageTreatment: "sepia",
      cardShape: "ticket",
      density: "balanced",
      watermark: true,
      grain: true,
      numbering: true,
      motion: { speed: 0.42, direction: "left", hoverLift: 2, parallax: false, pauseOnHover: true },
    },
  },

  operation: {
    primary: "table",
    supported: ["table", "pickup"],
  },

  capabilities: {
    ordering: true,
    delivery: false,
    pickup: true,
    tableOrders: true,
    waiterCall: true,
    reservation: true,
    story: true,
    coffeeCustomizer: false,
    beerTaps: false,
    iceCreamSizes: false,
    toppings: false,
    brunch: false,
    takeaway: true,
  },

  siteOverrides: {
    brand: {
      name: "CANTINA LA VEREDA",
      shortName: "La Vereda",
      descriptor: "Bodegón Tradicional & Cocina Porteña",
      tagline: "Platos abundantes, recetas familiares y sobremesa larga",
      description: "Bodegón tradicional con milanesas gigantes para compartir, pastas al fierrito y vermut de sifón.",
      logo: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=120&q=80",
      favicon: "/favicon.ico",
    },

    features: {
      ordering: true,
      delivery: false,
      pickup: true,
      tableOrders: true,
      waiterCall: true,
      reservation: true,
      story: true,
    },

    operation: {
      schedule: "Martes a Domingo · 12:00 a 16:00 y 20:00 a 01:00 hs",
      estimatedTime: {
        delivery: { min: 0, max: 0 },
        pickup: { min: 20, max: 30 },
        table: { min: 15, max: 28 },
      },
    },

    navigation: {
      links: [
        { label: "Inicio", href: "inicio" },
        { label: "Cantina", href: "historia" },
        { label: "Carta", href: "menu" },
        { label: "Reservar", href: "contacto" },
      ],
      cta: "Ver Carta",
    },

    ordering: {
      enabled: true,
      channels: ["web"] as const,
      fulfillment: ["onsite", "pickup"] as const,
      cashDiscountPercent: 10,
      paymentMethods: [
        { id: "cash", label: "Efectivo en Mesa", requiresProof: false },
        { id: "card", label: "Tarjeta de Débito / Crédito", requiresProof: false },
        { id: "transfer", label: "Transferencia / QR", requiresProof: true },
      ],
      whatsapp: {
        number: "549223000000",
        defaultMessage: "Hola La Vereda, quería hacer una reserva para el salón.",
        tableOrderMessage: "Hola, adjunto el pedido de la mesa.",
        labelCheckout: "Enviar comanda por WhatsApp",
      },
    },

    contact: {
      address: "11 de Septiembre 3120 (esquina Catamarca)",
      zone: "Barrio La Perla",
      city: "Mar del Plata",
      country: "Argentina",
      fullAddress: "11 de Septiembre 3120, Mar del Plata, Argentina",
      phone: "+54 9 223 555-0188",
      email: "cantina@lavereda.com",
      instagram: "https://instagram.com",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=11+de+Septiembre+3120+Mar+del+Plata",
      coordinates: {
        lat: -37.994211,
        lng: -57.548902,
        zoom: 16,
        latDisplay: "37°59′39″ S",
        lngDisplay: "57°32′56″ W",
      },
    },

    seo: {
      title: "Cantina La Vereda | Bodegón Porteño en Mar del Plata",
      description: "Milanesas gigantes para compartir, pastas caseras, vermut de sifón y sobremesas de familia en La Perla.",
      locale: "es_AR",
    },

    content: {
      hero: {
        eyebrow: "Cantina de Barrio · Cocina Clásica",
        titlePrefix: "Platos grandes",
        titleAccent: "y sobremesa.",
        subtitle: "Milanesas napolitanas al hierro para compartir, pastas al fierrito y vermut servido con soda de sifón.",
        cta: "Abrir Carta de Cantina",
        ctaHref: "menu",
        image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1920&q=85",
      },

      story: {
        eyebrow: "La Cantina",
        watermark: "MESA",
        titlePrefix: "Comer bien,",
        titleAccent: "entre muchos.",
        sectionTag: "La Cocina Tradicional",
        primaryDescription: "Nuestras porciones están pensadas para ir al centro de la mesa. Platos que se disfrutan con pan, tenedor y conversación.",
        secondaryDescription: "Cocinamos con recetas heredadas: salsas que hierven toda la mañana y carnes tiernizadas al momento.",
        backgroundImage: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=1800&q=85",
        labels: {
          processLine: "Sifón · Olla · Sobremesa",
          openArchive: "Explorar cantina",
          traceability: "De la Casa",
          closeSheet: "Cerrar Ficha",
        },
        archive: [
          {
            titulo: "Rebozado a Mano",
            subtitulo: "Carne Seleccionada",
            nota: "Peceto tiernizado, pan rallado fino y ajo con perejil fresco picado al momento.",
            origen: "Cocina La Vereda",
            src: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=1200&q=85",
          },
          {
            titulo: "Masa al Huevo",
            subtitulo: "Amasado Diario",
            nota: "Harina y yemas de campo sobadas a palote para lograr fideos que absorben el estofado.",
            origen: "Mesa de Pastas",
            src: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=85",
          },
          {
            titulo: "Sifón de Vidrio",
            subtitulo: "El Aperitivo",
            nota: "Gas carbónico enérgico para golpear el vermut y abrir el apetito antes de la comida.",
            origen: "Barra de Entrada",
            src: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=85",
          },
          {
            titulo: "Sobremesa Larga",
            subtitulo: "Salón Compartido",
            nota: "Mesas juntas, café en pocillo y copas que se quedan hasta que se apagan las luces.",
            origen: "Salón Central",
            src: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=85",
          },
        ],
      },

      productDetail: {
        fallbackTag: "Cantina",
        options: { required: "Elegir guarnición", optional: "Huevos fritos extra", requiredMark: "*", personalized: "Opción de plato" },
        notes: { label: "Aclaraciones a cocina", placeholder: "Ej. carne bien cocida, cebolla bien dorada..." },
        actions: {
          add: "Pedir al Centro",
          added: "Marchando",
          chooseRequired: "Elegir guarnición",
          decreaseQuantity: "Menos",
          increaseQuantity: "Más",
          close: "Volver a carta",
        },
      },

      cart: {
        eyebrow: "Mesa de Cantina",
        title: "Tu pedido",
        emptyTitle: "Mesa despejada",
        emptyDescription: "Agregá tortillas, milanesas o pastas para marchar la comida.",
        productSingular: "fuente",
        productPlural: "fuentes",
        remove: "Quitar",
        subtotal: "Subtotal cantina",
        continueDescription: "Revisá los platos antes de confirmarle al mozo.",
        checkoutButton: "Marchar a Cocina",
        close: "Cerrar",
        closeOrder: "Cerrar mesa",
      },

      checkout: {
        disabled: { title: "Cocina cerrada", description: "El bodegón abre para los turnos de almuerzo y cena." },
        header: { backLabel: "Carta", title: "Comanda de la Cantina", onlineLabel: "Para Llevar", tablePrefix: "Mesa" },
        hero: { tableLabel: "Mesa", onlineLabel: "Comanda", title: "Tus Platos", description: "Revisá la comida elegida antes de que empiece a salir." },
        selection: { label: "Platos a compartir", units: "platos", perUnit: "c/u", remove: "Quitar", decrease: "Menos", increase: "Más" },
        empty: { title: "No agregaste platos", description: "Elegí de la carta de milanesas o pastas.", button: "Ver Carta" },
        form: {
          fulfillmentLabel: "Modalidad",
          delivery: "Envío",
          pickup: "Retiro en Cantina",
          customerNameLabel: "Nombre para el ticket",
          customerNamePlaceholder: "Tu nombre",
          addressLabel: "Dirección",
          addressPlaceholder: "Calle y número",
          paymentLabel: "Forma de Pago",
          notesLabel: "Aclaraciones para la cocina",
          notesDeliveryPlaceholder: "Indicaciones para el retiro...",
          notesTablePlaceholder: "Ej. el flan al final, soda con hielo...",
        },
        summary: { subtotal: "Total consumo", cashPrefix: "Efectivo", total: "Total a pagar", completedLabel: "Listo para salir", estimatedLabel: "Salida de cocina en" },
        actions: { processing: "Marchando pedido...", sendToKitchen: "Marchar Comanda", newOrder: "Pedir otro plato", openWhatsApp: "Confirmar por WhatsApp", continueArrow: "Continuar" },
        confirmation: {
          preparedLabel: "Comanda Lista",
          confirmedLabel: "Olla y Plancha Marchando",
          whatsAppDescription: "Enviá el mensaje para que el cocinero baje las fuentes.",
          tableDescriptionPrefix: "La cocina de la cantina ya recibió tu pedido",
          kitchenTableSuffix: "",
          preparedToastTitle: "Comanda lista",
          preparedToastDescription: "Se abrirá WhatsApp con el pedido armado.",
          confirmedToastTitle: "Platos marchando",
          confirmedToastDescriptionPrefix: "Las fuentes están saliendo",
        },
        validation: {
          emptyTitle: "Mesa vacía",
          emptyDescription: "Agregá al menos un plato.",
          nameTitle: "Nombre requerido",
          nameDescription: "El mozo necesita identificar la mesa.",
          addressTitle: "Falta dirección",
          addressDescription: "Ingresá a dónde enviamos el pedido.",
          submitErrorTitle: "Error al enviar comanda",
          submitErrorDescription: "Comprobá tu conexión con el salón.",
        },
        helper: { table: "La comanda ingresa directamente a las ollas de la cantina.", online: "Se abrirá WhatsApp con el pedido listo." },
        aria: { decrease: "Disminuir", increase: "Aumentar", remove: "Quitar", openWhatsApp: "Abrir WhatsApp", newOrder: "Pedir otra vez" },
      },

      menuUi: {
        productPersonalizable: "Con guarnición",
        viewDetail: "Detalle del plato",
        prepLabel: "Tiempo de olla",
        fallbackKitchen: "Cocina casera",
        choose: "Elegir guarnición",
        added: "Marchando",
        add: "Pedir",
        ariaViewProduct: "Ver plato",
        categoryCountSingular: "plato",
        categoryCountPlural: "platos",
        allCategories: "Todos",
        listView: "Carta",
        gridView: "Platos",
        ariaListView: "Ver como carta",
        ariaGridView: "Ver como fotos",
        ariaAllCategories: "Ver todas las opciones",
      },

      tableUi: {
        serviceLabel: "Servicio de Cantina",
        tablePrefix: "Mesa",
        waiterButton: "Llamar al Mozo",
        allCategories: "Toda la carta",
        listView: "Carta",
        gridView: "Platos",
        ariaListView: "Ver carta",
        ariaGridView: "Ver platos",
        ariaWaiter: "Solicitar asistencia",
      },

      cartUi: { ariaOpen: "Abrir comanda" },
      navbarUi: {
        themeDark: "CANTINA",
        themeLight: "DÍA",
        ariaChangeTheme: "Cambiar ambiente",
        ariaOpenOrder: "Ver comanda",
        ariaOpenMenu: "Abrir carta",
        ariaCloseMenu: "Cerrar carta",
        mobileNavigationLabel: "Secciones",
      },
      contactUi: { waitTimeTableLabel: "Cocina", waitTimeDeliveryLabel: "Para llevar", minutesSuffix: "min" },

      menu: {
        eyebrow: "Fuentes Grandes & Pastas",
        title: "Carta de Cantina",
        subtitle: "Milanesas napolitanas al hierro para dos, pastas caseras al huevo y vermut con soda de sifón.",
      },

      ctaTransition: {
        eyebrow: "Mesas para Grupos",
        titlePrefix: "Juntá a la familia",
        titleAccent: "en La Vereda.",
        description: "Reservá mesas grandes para cumpleaños, domingos al mediodía y celebraciones entre amigos.",
        buttonText: "Reservar Mesa Grande",
        image: "https://images.unsplash.com/photo-1604908554027-1d3a6c0d6f5a?auto=format&fit=crop&w=1920&q=85",
      },

      contact: {
        eyebrow: "Salón & Reservas",
        statusBadge: "Cantina Abierta",
        mainLabel: "Salón La Perla",
        title: "Vení a comer bien.",
        formEyebrow: "Reservas de Grupo",
        formTitulo: "¿Querés juntar a toda la familia?",
        formSubtitulo: "Mesas largas preparadas con fuentes al medio para compartir sin apuro.",
        nameLabel: "Nombre y apellido",
        phoneLabel: "WhatsApp",
        emailLabel: "Correo",
        messageLabel: "Día, hora y cantidad de adultos y chicos",
        submitSending: "Abriendo WhatsApp...",
        submitSent: "Mensaje enviado ✓",
        botonEnviar: "Avisar a la Cantina",
        addressLabel: "Bodegón",
        scheduleLabel: "Horarios de Salón",
        mapEyebrow: "Ubicación",
        directionsButton: "Cómo llegar",
        instagramLabel: "Instagram",
        whatsappLabel: "WhatsApp",
        copyButton: "Copiar",
        copiedButton: "Copiado",
        mapsButton: "Abrir Maps",
        receptionPrompt: "¿Querés celebrar un cumpleaños con menú fijo?",
        receptionButton: "Hablar con el Encargado",
      },

      waiterModal: {
        eyebrow: "Mesa Familiar",
        callTitle: "Llamar al Mozo",
        callSubtitle: "Pedir más pan, soda, hielo o consultar el plato del día",
        callMessage: "Atención solicitada en mesa",
        billTitle: "Pedir la Cuenta",
        billSubtitle: "Efectivo con 10% de ahorro o tarjetas",
        paymentPrompt: "¿Cómo preferís pagar?",
        sentTitle: "Aviso recibido",
        sentSubtitle: "El mozo se acerca a la mesa:",
        backButton: "Volver",
        confirmButton: "Confirmar",
        errorMessage: "Error al comunicar con la caja.",
      },

      footer: {
        backgroundImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1920&q=85",
        description: "Cantina La Vereda · Bodegón Tradicional & Cocina Criolla",
        credits: "Gastro Engine Core",
        navigationLabel: "Navegación",
        contactLabel: "Contacto",
        establishmentLabel: "El Bodegón",
        hoursLabel: "Turnos",
        socialsLabel: "Comunidad",
        instagramLabel: "Instagram",
        whatsappLabel: "WhatsApp",
        locationLabel: "Dirección",
        identityLabel: "Tradición",
        backToTop: "Volver arriba",
      },
    },
  },

  menu: {
    categories: bodegonCategories,
    products: bodegonProducts,
  },
};