import type { GastroPreset } from "./types";

const breweryCategories = [
  { id: "canillas", name: "Pizarra de Canillas", description: "Lotes propios rotativos servidos a 2°C directamente desde la cámara." },
  { id: "burgers", name: "Smash & Grill", description: "Medallones aplastados sobre plancha de hierro hirviendo." },
  { id: "tapeo", name: "Tapeo Cervecero", description: "Papas cargadas, pollo crocante y tablas para el centro de la mesa." },
  { id: "growlers", name: "Growlers & Latas", description: "Recargas y botellones presurizados para llevar del TAP que prefieras." },
];

const beerFormatOptions = [
  { id: "pinta-473", name: "Pinta 473 ml", priceDelta: 0 },
  { id: "media-350", name: "Media Pinta 350 ml", priceDelta: -900 },
  { id: "growler-19", name: "Botellón Growler 1.9 L", priceDelta: 12400 },
];

const breweryProducts = [
  {
    id: "tap-01-pilsner",
    categoryId: "canillas",
    name: "TAP 01 · Bohemian Pils",
    description: "TAP 01 · Estilo Bohemian Pilsner · IBU 34 · ABV 5.1%. Final seco y herbal.",
    price: 6900,
    image: "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 01", "Lager"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-01", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-02-honey",
    categoryId: "canillas",
    name: "TAP 02 · Honey Ale",
    description: "TAP 02 · Estilo Honey Ale · IBU 19 · ABV 5.4%. Miel suave y final floral.",
    price: 7000,
    image: "https://images.unsplash.com/photo-1567696911980-2eed69a46042?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 02", "Honey"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-02", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-03-apa",
    categoryId: "canillas",
    name: "TAP 03 · American Pale Ale",
    description: "TAP 03 · Estilo APA · IBU 42 · ABV 5.7%. Cítrica y balanceada.",
    price: 7100,
    image: "https://images.unsplash.com/photo-1436076863939-06870fe779c2?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 03", "APA"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-03", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-04-west-coast",
    categoryId: "canillas",
    name: "TAP 04 · West Coast IPA",
    description: "TAP 04 · Estilo West Coast IPA · IBU 62 · ABV 6.7%. Resina, pomelo y final seco.",
    price: 7600,
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 04", "Best Seller"],
    prepTime: "2 min",
    isFeatured: true,
    optionGroups: [{ id: "formato-tap-04", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-05-red-ipa",
    categoryId: "canillas",
    name: "TAP 05 · Red IPA",
    description: "TAP 05 · Estilo Red IPA · IBU 58 · ABV 6.4%. Caramelo tostado y lúpulo cítrico.",
    price: 7500,
    image: "https://images.unsplash.com/photo-1618885472179-5e474019f2a9?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 05", "Maltosa"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-05", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-06-session-ipa",
    categoryId: "canillas",
    name: "TAP 06 · Session IPA",
    description: "TAP 06 · Estilo Session IPA · IBU 38 · ABV 4.6%. Bebible, cítrica y ligera.",
    price: 6800,
    image: "https://images.unsplash.com/photo-1471421298428-1513ab720a8e?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 06", "Session"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-06", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-07-hazy-ipa",
    categoryId: "canillas",
    name: "TAP 07 · Hazy Juicy IPA",
    description: "TAP 07 · Estilo Hazy IPA · IBU 30 · ABV 6.2%. Trazos tropicales y cuerpo sedoso.",
    price: 7900,
    image: "https://images.unsplash.com/photo-1571767454098-246b94fbcf70?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 07", "Doble Dry-Hop"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-07", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-08-porter",
    categoryId: "canillas",
    name: "TAP 08 · Robust Porter",
    description: "TAP 08 · Estilo Porter · IBU 33 · ABV 5.9%. Cacao y café tostado.",
    price: 7300,
    image: "https://images.unsplash.com/photo-1518085250887-2f903c200fee?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 08", "Oscura"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-08", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-09-irish-red",
    categoryId: "canillas",
    name: "TAP 09 · Irish Red",
    description: "TAP 09 · Estilo Irish Red Ale · IBU 25 · ABV 5.0%. Toffee y pan tostado.",
    price: 7000,
    image: "https://images.unsplash.com/photo-1559526323-cb2f2fe2591b?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 09", "Maltosa"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-09", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-10-kolsch",
    categoryId: "canillas",
    name: "TAP 10 · Kölsch",
    description: "TAP 10 · Estilo Kölsch · IBU 24 · ABV 4.9%. Ligera con notas a cereal.",
    price: 6800,
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 10", "Refrescante"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-10", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-11-belgian-blonde",
    categoryId: "canillas",
    name: "TAP 11 · Belgian Blonde",
    description: "TAP 11 · Estilo Belgian Blonde · IBU 28 · ABV 6.3%. Especias y fruta madura.",
    price: 7400,
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 11", "Belga"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-11", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "tap-12-imperial-stout",
    categoryId: "canillas",
    name: "TAP 12 · Imperial Stout Nitro",
    description: "TAP 12 · Estilo Imperial Stout Nitro · IBU 40 · ABV 7.5%. Cremosa y achocolatada.",
    price: 7800,
    image: "https://images.unsplash.com/photo-1532634922-8fe0b757fb13?auto=format&fit=crop&w=1600&q=85",
    tags: ["TAP 12", "Nitro"],
    prepTime: "2 min",
    optionGroups: [{ id: "formato-tap-12", name: "Formato", type: "single", required: true, items: beerFormatOptions }],
  },
  {
    id: "smash-doble-bacon",
    categoryId: "burgers",
    name: "Doble Smash Bacon Jam",
    description: "Dos medallones de 110g smash, queso cheddar inglés, mermelada de panceta y pan de papa tostado.",
    price: 15400,
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=1600&q=85",
    tags: ["Smash Burger", "Pan de papa"],
    prepTime: "14 min",
    isFeatured: true,
    optionGroups: [
      {
        id: "smash-medallones",
        name: "Medallones",
        type: "single",
        required: true,
        items: [
          { id: "smash-2", name: "Doble smash (2 medallones)", priceDelta: 0 },
          { id: "smash-3", name: "Triple smash (3 medallones)", priceDelta: 3400 },
          { id: "smash-4", name: "Cuádruple smash (4 medallones)", priceDelta: 6700 },
        ],
      },
      {
        id: "smash-aderezos",
        name: "Aderezos ahumados",
        type: "multiple",
        maxSelections: 2,
        items: [
          { id: "bbq-ahumada", name: "BBQ ahumada con bourbon", priceDelta: 700 },
          { id: "alioli-brasa", name: "Alioli de ajo asado", priceDelta: 700 },
          { id: "mostaza-malta", name: "Mostaza de malta y miel", priceDelta: 700 },
        ],
      },
    ],
  },
  {
    id: "papas-bacon-cheddar",
    categoryId: "tapeo",
    name: "Papas Rústicas Hop District",
    description: "Papas triple cocción con salsa cheddar de barril, panceta crocante y ciboulette fresco.",
    price: 10800,
    image: "https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&w=1600&q=85",
    tags: ["Para compartir"],
    prepTime: "10 min",
  },
  {
    id: "growler-recarga",
    categoryId: "growlers",
    name: "Botellón Growler 1.9L Vidrio",
    description: "Botellón ámbar con recarga completa de cualquier canilla de la pizarra para llevar.",
    price: 18200,
    image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1600&q=85",
    tags: ["Take Away"],
    prepTime: "5 min",
  },
];

export const breweryPreset: GastroPreset = {
  id: "brewery",
  label: "Cervecería Artesanal & Taproom",

  theme: {
    mode: "dark",
    accent: "#D49A32",
    accentStrong: "#F0BE5B",
    accentContrast: "#080A0C",

    colors: {
      light: {
        bg: "#F2F4F7",
        bgElevated: "#FFFFFF",
        surface: "#FFFFFF",
        surfaceElevated: "#E2E7EE",
        surfaceInverse: "#0D1117",
        text: "#111827",
        textMuted: "#4B5563",
        textSubtle: "#6B7280",
        accent: "#B47C1E",
        accentStrong: "#8C5E10",
        accentContrast: "#FFFFFF",
        accentSoft: "rgba(180, 124, 30, 0.12)",
        accentFaint: "rgba(180, 124, 30, 0.05)",
        accentBorder: "rgba(180, 124, 30, 0.35)",
        border: "rgba(17, 24, 39, 0.10)",
        borderStrong: "rgba(17, 24, 39, 0.20)",
        overlay: "rgba(242, 244, 247, 0.90)",
        control: "rgba(17, 24, 39, 0.04)",
        controlHover: "rgba(17, 24, 39, 0.08)",
        success: "#059669",
        warning: "#B45309",
        danger: "#DC2626",
      },
      dark: {
        bg: "#080A0C",
        bgElevated: "#0E1217",
        surface: "#12171E",
        surfaceElevated: "#18202A",
        surfaceInverse: "#F5EFE4",
        text: "#F5EFE4",
        textMuted: "#B8AEA0",
        textSubtle: "#80786C",
        accent: "#D49A32",
        accentStrong: "#F0BE5B",
        accentContrast: "#080A0C",
        accentSoft: "rgba(212, 154, 50, 0.16)",
        accentFaint: "rgba(212, 154, 50, 0.08)",
        accentBorder: "rgba(212, 154, 50, 0.38)",
        border: "rgba(245, 239, 228, 0.11)",
        borderStrong: "rgba(245, 239, 228, 0.22)",
        overlay: "rgba(8, 10, 12, 0.92)",
        control: "rgba(245, 239, 228, 0.06)",
        controlHover: "rgba(245, 239, 228, 0.10)",
        success: "#34D399",
        warning: "#F59E0B",
        danger: "#F87171",
      },
    },

    typography: {
      display: "'Space Grotesk', -apple-system, sans-serif",
      body: "Inter, Arial, sans-serif",
      ui: "Inter, Arial, sans-serif",
      mono: "'JetBrains Mono', monospace",
    },
  },

  visual: {
    navbar: "editorial",
    hero: "industrial",
    heroStyle: {
      variant: "industrial",
      imageTreatment: "highContrast",
      overlay: "edge",
      composition: "split",
      ctaShape: "square",
      grain: true,
      parallax: false,
      intensity: 1.15,
    },
    menu: "catalog",
    productCard: "photo",
    contact: "map",
    cta: "immersive",
    footer: "editorial",
    story: {
      variant: "taproom",
      layout: "marquee",
      imageTreatment: "highContrast",
      cardShape: "poster",
      density: "dense",
      watermark: true,
      grain: true,
      numbering: true,
      motion: { speed: 1.15, direction: "right", hoverLift: 8, parallax: false, pauseOnHover: true },
    },
  },

  operation: {
    primary: "table",
    supported: ["table", "pickup", "counter"],
  },

  capabilities: {
    ordering: true,
    delivery: false,
    pickup: true,
    tableOrders: true,
    waiterCall: true,
    reservation: false,
    story: true,
    coffeeCustomizer: false,
    beerTaps: true,
    iceCreamSizes: false,
    toppings: false,
    brunch: false,
    takeaway: true,
  },

  siteOverrides: {
    brand: {
      name: "HOP DISTRICT",
      shortName: "Hop",
      descriptor: "Independent Taproom & Brewhouse",
      tagline: "Canillas sin pasteurizar, smash burgers y noches de barra",
      description: "Taproom cervecero independiente con cámara de frío a la vista, pizarras rotativas y cocina al hierro.",
      logo: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=120&q=80",
      favicon: "/favicon.ico",
    },

    features: {
      ordering: true,
      delivery: false,
      pickup: true,
      tableOrders: true,
      waiterCall: true,
      reservation: false,
      story: true,
    },

    operation: {
      schedule: "Martes a Domingo · 18:00 a 02:30 hs",
      estimatedTime: {
        delivery: { min: 0, max: 0 },
        pickup: { min: 15, max: 25 },
        table: { min: 10, max: 20 },
      },
    },

    navigation: {
      links: [
        { label: "Taproom", href: "inicio" },
        { label: "Fábrica", href: "historia" },
        { label: "Pizarra", href: "menu" },
        { label: "Visitanos", href: "contacto" },
      ],
      cta: "Ver Canillas",
    },

    ordering: {
      enabled: true,
      channels: ["web"] as const,
      fulfillment: ["pickup", "onsite"] as const,
      cashDiscountPercent: 10,
      paymentMethods: [
        { id: "cash", label: "Efectivo en Barra", requiresProof: false },
        { id: "card", label: "Tarjeta de Débito/Crédito", requiresProof: false },
        { id: "transfer", label: "Transferencia / QR", requiresProof: true },
      ],
      whatsapp: {
        number: "549223000000",
        defaultMessage: "Hola Hop District, quiero pedir para retirar por el taproom.",
        tableOrderMessage: "Hola, adjunto mi pedido desde mesa.",
        labelCheckout: "Enviar comanda por WhatsApp",
      },
    },

    contact: {
      address: "Rawson 1420 (esquina Olavarría)",
      zone: "Zona Güemes",
      city: "Mar del Plata",
      country: "Argentina",
      fullAddress: "Rawson 1420, Mar del Plata, Argentina",
      phone: "+54 9 223 555-0199",
      email: "taproom@hopdistrict.com",
      instagram: "https://instagram.com",
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Rawson+1420+Mar+del+Plata",
      coordinates: {
        lat: -38.014522,
        lng: -57.541289,
        zoom: 16,
        latDisplay: "38°00′52″ S",
        lngDisplay: "57°32′28″ W",
      },
    },

    seo: {
      title: "Hop District | Taproom Cervecero & Smash Burgers",
      description: "16 canillas de cerveza artesanal independiente, smash burgers dobles y growlers en Mar del Plata.",
      locale: "es_AR",
    },

    content: {
      hero: {
        eyebrow: "Taproom · 16 Canillas Vivas",
        titlePrefix: "Lúpulo fresco",
        titleAccent: "directo del tanque.",
        subtitle: "Cerveza independiente sin pasteurizar, smash burgers dobles al hierro y tapeo urbano para compartir.",
        cta: "Ver Canillas en Vivo",
        ctaHref: "menu",
        image: "https://images.unsplash.com/photo-1575037614876-c38a4d44f5b8?auto=format&fit=crop&w=1920&q=85",
      },

      story: {
        eyebrow: "La Fábrica",
        watermark: "HOPS",
        titlePrefix: "Cerveza viva",
        titleAccent: "sin filtrar.",
        sectionTag: "Registro de Cocción",
        primaryDescription: "Cocinamos en lotes de 1.000 litros sin conservantes. Cada estilo pasa por un reposo en frío para decantar de forma natural.",
        secondaryDescription: "El lúpulo en flor se incorpora en maduración para extraer terpenos y aromas cítricos puros.",
        backgroundImage: "https://images.unsplash.com/photo-1584225064785-c62a8b43d148?auto=format&fit=crop&w=1800&q=85",
        labels: {
          processLine: "Grano · Macerado · Fermentador",
          openArchive: "Explorar fábrica",
          traceability: "Lote & ABV",
          closeSheet: "Cerrar Ficha",
        },
        archive: [
          {
            titulo: "Lúpulo en Flor",
            subtitulo: "Dry Hopping Frío",
            nota: "Conos seleccionados en cosecha para liberar aceites aromáticos sin sumar amargor astringente.",
            origen: "Alto Valle del Río Negro",
            src: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=85",
          },
          {
            titulo: "Maltas Especiales",
            subtitulo: "Cereal Tostado",
            nota: "Cebada malteada que aporta el color cobrizo, notas a galleta y el cuerpo denso de nuestras cervezas.",
            origen: "Maltería Pampa",
            src: "https://images.unsplash.com/photo-1608270199144-8c82ebfcdd4a?auto=format&fit=crop&w=1200&q=85",
          },
          {
            titulo: "Tanques Isobáricos",
            subtitulo: "Carbonatación Natural",
            nota: "Mantenemos los tanques a 0°C para retener la burbuja fina originada por la propia levadura.",
            origen: "Sala de Maduración",
            src: "https://images.unsplash.com/photo-1559526323-cb2f2fe2591b?auto=format&fit=crop&w=1200&q=85",
          },
          {
            titulo: "Plancha de Hierro",
            subtitulo: "Smash Burgers",
            nota: "Carne aplastada a 260°C para lograr la reacción de Maillard que forma una costra crocante y jugosa.",
            origen: "Cocina Hop District",
            src: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=85",
          },
        ],
      },

      productDetail: {
        fallbackTag: "Pizarra",
        options: { required: "Elegir formato", optional: "Toppings extra", requiredMark: "*", personalized: "Configurar pinta" },
        notes: { label: "Aclaraciones para la barra", placeholder: "Ej. burger sin pepinillos, vaso frío..." },
        actions: {
          add: "Pedir Pinta",
          added: "Marchando",
          chooseRequired: "Elegir tamaño de pinta",
          decreaseQuantity: "Menos",
          increaseQuantity: "Más",
          close: "Volver a pizarra",
        },
      },

      cart: {
        eyebrow: "Comanda",
        title: "Tu ronda",
        emptyTitle: "Sin birras en mesa",
        emptyDescription: "Revisá las canillas de la pizarra para armar la primera ronda.",
        productSingular: "pinta / plato",
        productPlural: "pintas / platos",
        remove: "Bajar de comanda",
        subtotal: "Subtotal barra",
        continueDescription: "Confirmá tu pedido para que empiece a salir.",
        checkoutButton: "Marchar Comanda",
        close: "Cerrar",
        closeOrder: "Cerrar comanda",
      },

      checkout: {
        disabled: { title: "Canillas cerradas", description: "El taproom se encuentra fuera de horario de servicio." },
        header: { backLabel: "Pizarra", title: "Comanda del Taproom", onlineLabel: "Take Away", tablePrefix: "Mesa" },
        hero: { tableLabel: "Mesa", onlineLabel: "Take Away", title: "Tu Ronda", description: "Revisá las pintas y comidas antes de enviar la comanda." },
        selection: { label: "Detalle de ronda", units: "ítems", perUnit: "c/u", remove: "Quitar", decrease: "Menos", increase: "Más" },
        empty: { title: "No pediste nada aún", description: "Elegí de las canillas o de la plancha para comenzar.", button: "Ver Pizarra" },
        form: {
          fulfillmentLabel: "Modalidad",
          delivery: "Envío",
          pickup: "Retiro en Taproom",
          customerNameLabel: "Nombre para el ticket",
          customerNamePlaceholder: "Tu nombre o apodo",
          addressLabel: "Dirección",
          addressPlaceholder: "Calle y número",
          paymentLabel: "Medio de Pago",
          notesLabel: "Aclaraciones a cocina / barra",
          notesDeliveryPlaceholder: "Ej. timbre que no anda, llamar al llegar...",
          notesTablePlaceholder: "Ej. la cerveza primero, aderezos aparte...",
        },
        summary: { subtotal: "Total consumo", cashPrefix: "Efectivo en barra", total: "Total a pagar", completedLabel: "Listo para marchar", estimatedLabel: "Salida estimada" },
        actions: { processing: "Enviando comanda...", sendToKitchen: "Marchar a Cocina/Barra", newOrder: "Pedir otra ronda", openWhatsApp: "Enviar por WhatsApp", continueArrow: "Continuar" },
        confirmation: {
          preparedLabel: "Ronda Lista",
          confirmedLabel: "Comanda Marchando",
          whatsAppDescription: "Enviá el mensaje para que el bartender sirva tus pintas.",
          tableDescriptionPrefix: "La cocina y la barra ya tienen tu pedido",
          kitchenTableSuffix: "",
          preparedToastTitle: "Ronda confirmada",
          preparedToastDescription: "Se abrirá WhatsApp con el pedido detallado.",
          confirmedToastTitle: "Comanda en marcha",
          confirmedToastDescriptionPrefix: "El pedido fue enviado a la barra",
        },
        validation: {
          emptyTitle: "Comanda vacía",
          emptyDescription: "Sumá al menos una pinta o comida.",
          nameTitle: "Falta tu nombre",
          nameDescription: "El bartender necesita saber a quién llamar.",
          addressTitle: "Falta la dirección",
          addressDescription: "Ingresá dónde enviamos el pedido.",
          submitErrorTitle: "Error al enviar comanda",
          submitErrorDescription: "Comprobá tu conexión con el taproom.",
        },
        helper: { table: "La comanda ingresa directamente a las pantallas de barra y plancha.", online: "Se abrirá WhatsApp con el pedido listo para despachar." },
        aria: { decrease: "Disminuir", increase: "Aumentar", remove: "Quitar", openWhatsApp: "Abrir WhatsApp", newOrder: "Pedir otra ronda" },
      },

      menuUi: {
        productPersonalizable: "Formatos",
        viewDetail: "Ficha técnica",
        prepLabel: "Tirada en",
        fallbackKitchen: "Canillas vivas",
        choose: "Elegir pinta",
        added: "Anotado",
        add: "Pedir",
        ariaViewProduct: "Ver ficha de",
        categoryCountSingular: "estilo",
        categoryCountPlural: "estilos",
        allCategories: "Todas",
        listView: "Pizarra",
        gridView: "Grilla",
        ariaListView: "Ver como lista de pizarra",
        ariaGridView: "Ver como grilla",
        ariaAllCategories: "Ver todas las canillas",
      },

      tableUi: {
        serviceLabel: "Servicio de Taproom",
        tablePrefix: "Mesa",
        waiterButton: "Llamar Bartender",
        allCategories: "Pizarra completa",
        listView: "Lista",
        gridView: "Grilla",
        ariaListView: "Ver lista",
        ariaGridView: "Ver grilla",
        ariaWaiter: "Solicitar asistencia de barra",
      },

      cartUi: { ariaOpen: "Abrir comanda" },
      navbarUi: {
        themeDark: "TAPROOM",
        themeLight: "DÍA",
        ariaChangeTheme: "Cambiar ambiente",
        ariaOpenOrder: "Ver ronda",
        ariaOpenMenu: "Abrir pizarra",
        ariaCloseMenu: "Cerrar pizarra",
        mobileNavigationLabel: "Secciones",
      },
      contactUi: { waitTimeTableLabel: "Barra", waitTimeDeliveryLabel: "Take Away", minutesSuffix: "min" },

      menu: {
        eyebrow: "Pizarras & Planchas",
        title: "Pizarra de Canillas",
        subtitle: "16 estilos artesanales sin pasteurizar, smash burgers dobles y tapeo para compartir.",
      },

      ctaTransition: {
        eyebrow: "Noches de Barra",
        titlePrefix: "Juntate en el",
        titleAccent: "Taproom.",
        description: "Mesas largas comunitarias, música y la pizarra de canillas rotando todas las semanas.",
        buttonText: "Ver Ubicación & Horarios",
        image: "https://images.unsplash.com/photo-1518085250887-2f903c200fee?auto=format&fit=crop&w=1920&q=85",
      },

      contact: {
        eyebrow: "Dónde Estamos",
        statusBadge: "Canillas Abiertas",
        mainLabel: "Taproom Güemes",
        title: "Vení a probar.",
        formEyebrow: "Contacto",
        formTitulo: "¿Querés reservar para un grupo grande?",
        formSubtitulo: "Cumpleaños, juntadas de amigos y eventos con barril propio.",
        nameLabel: "Nombre",
        phoneLabel: "WhatsApp",
        emailLabel: "Correo",
        messageLabel: "Cantidad de personas y fecha",
        submitSending: "Abriendo WhatsApp...",
        submitSent: "Mensaje enviado ✓",
        botonEnviar: "Consultar con Taproom",
        addressLabel: "Ubicación",
        scheduleLabel: "Horarios de Canilla",
        mapEyebrow: "Mapa",
        directionsButton: "Cómo llegar",
        instagramLabel: "Instagram",
        whatsappLabel: "WhatsApp",
        copyButton: "Copiar",
        copiedButton: "Copiado",
        mapsButton: "Abrir Maps",
        receptionPrompt: "¿Buscás barriles para tu evento privado?",
        receptionButton: "Hablar con Fábrica",
      },

      waiterModal: {
        eyebrow: "Asistencia de Barra",
        callTitle: "Llamar al Bartender",
        callSubtitle: "Dudas sobre IBU, estilos o recomendación de la casa",
        callMessage: "Consulta sobre las canillas del día",
        billTitle: "Pedir la Cuenta",
        billSubtitle: "Efectivo, Tarjetas o Mercado Pago",
        paymentPrompt: "¿Cómo abonás?",
        sentTitle: "Bartender en camino",
        sentSubtitle: "Ya registramos tu aviso en la barra:",
        backButton: "Volver",
        confirmButton: "Confirmar aviso",
        errorMessage: "Error al comunicar con la barra.",
      },

      footer: {
        backgroundImage: "https://images.unsplash.com/photo-1538488881523-294da0c87b63?auto=format&fit=crop&w=1920&q=85",
        description: "Hop District Brewhouse · Taproom Independiente & Burgers",
        credits: "Gastro Engine Core",
        navigationLabel: "Navegación",
        contactLabel: "Contacto",
        establishmentLabel: "El Taproom",
        hoursLabel: "Horarios",
        socialsLabel: "Comunidad",
        instagramLabel: "Instagram",
        whatsappLabel: "WhatsApp",
        locationLabel: "Dirección",
        identityLabel: "Cultura",
        backToTop: "Volver arriba",
      },
    },
  },

  menu: {
    categories: breweryCategories,
    products: breweryProducts,
  },
};