import type { MenuCategory, MenuProduct } from "@/data/menu";
import type { GastroPreset } from "./types";

const cateringCategories: MenuCategory[] = [
  { id: "recepcion", name: "Finger Food & Recepción", description: "Bocados individuales diseñados para comer de pie en servicio continuo." },
  { id: "stations", name: "Estaciones en Vivo", description: "Puestos gastronómicos interactivos con chefs finalizando platos al momento." },
  { id: "boxes", name: "Boxes Corporativos", description: "Menús individuales premium en packaging térmico biodegradable para empresas." },
  { id: "sweet", name: "Mesa Dulce & Petit Fours", description: "Bocados de pastelería fina, macarons y tarteletas individuales." },
];

const cateringProducts: MenuProduct[] = [
  {
    id: "live-pasta-station",
    categoryId: "stations",
    name: "Estación de Pastas al Parmesano",
    description: "Pasta fresca artesanal terminada en vivo dentro de una rueda de queso parmesano con trufa negra.",
    price: 32000,
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1600&q=85",
    tags: ["Live Cooking", "Servicio por persona"],
    prepTime: "30 min",
    isFeatured: true,
  },
  {
    id: "box-roast-beef-catering",
    categoryId: "boxes",
    name: "Lunch Box Roast Beef & Vegetales Asados",
    description: "Láminas de roast beef al punto, papines al romero, vegetales glaseados y postre individual.",
    price: 18900,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1600&q=85",
    tags: ["Individual", "Corporativo"],
    prepTime: "25 min",
  },
  {
    id: "finger-food-pack",
    categoryId: "recepcion",
    name: "Selección Cocktail Finger Food (24 piezas)",
    description: "Bruschettas de burrata, mini brioche de pastrami, pinchos de salmón curado y hojaldres de queso brie.",
    price: 28500,
    image: "https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=1600&q=85",
    tags: ["Para 4 personas"],
    prepTime: "20 min",
    isFeatured: true,
  },
  {
    id: "mesa-dulce-signature",
    categoryId: "sweet",
    name: "Mesa Dulce Signature & Macarons (36 bocados)",
    description: "Mini tarteletas de frambuesa, verrines de chocolate belga, macarons de pistacho y trufas de cacao puro.",
    price: 26800,
    image: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=1600&q=85",
    tags: ["Mesa dulce"],
    prepTime: "20 min",
  },
];

export const cateringPreset: GastroPreset = {
  id: "catering",
  label: "Catering Premium & Eventos",
  theme: {
    mode: "dark",
    accent: "#CBB079",
    accentStrong: "#E6D3A7",
    accentContrast: "#0A0908",
    typography: {
      display: "var(--font-display, Georgia, serif)",
      body: "var(--font-sans, Arial, sans-serif)",
      ui: "var(--font-sans, Arial, sans-serif)",
      mono: "var(--font-mono, monospace)",
    },
    colors: {
      dark: {
        bg: "#0A0908",
        bgElevated: "#110F0D",
        surface: "#141210",
        surfaceElevated: "#1C1916",
        surfaceInverse: "#F7F2E9",
        text: "#F7F2E9",
        textMuted: "#C7BCAE",
        textSubtle: "#8A8073",
        accent: "#CBB079",
        accentStrong: "#E6D3A7",
        accentContrast: "#0A0908",
        accentSoft: "rgba(203,176,121,0.15)",
        accentFaint: "rgba(203,176,121,0.07)",
        accentBorder: "rgba(203,176,121,0.35)",
        border: "rgba(247,242,233,0.1)",
        borderStrong: "rgba(247,242,233,0.2)",
        overlay: "rgba(10,9,8,0.92)",
        control: "rgba(247,242,233,0.05)",
        controlHover: "rgba(247,242,233,0.09)",
        success: "#34D399",
        warning: "#F59E0B",
        danger: "#F87171",
      },
    },
  },
  visual: {
    navbar: "minimal",
    hero: "hospitality",
    heroStyle: {
      variant: "hospitality",
      imageTreatment: "natural",
      overlay: "editorial",
      composition: "split",
      ctaShape: "outline",
      grain: false,
      parallax: true,
      intensity: 0.88,
    },
    menu: "catalog",
    productCard: "clean",
    contact: "split",
    cta: "editorial",
    footer: "minimal",
    story: {
      variant: "hospitality",
      layout: "editorial",
      imageTreatment: "natural",
      cardShape: "poster",
      density: "airy",
      watermark: false,
      grain: false,
      numbering: true,
      motion: { speed: 0.5, direction: "left", hoverLift: 5, parallax: true, pauseOnHover: true },
    },
  },
  operation: { primary: "delivery", supported: ["delivery", "pickup"] },
  capabilities: {
    ordering: true,
    delivery: true,
    pickup: true,
    tableOrders: false,
    waiterCall: false,
    reservation: true,
    story: true,
    coffeeCustomizer: true,
    beerTaps: false,
    iceCreamSizes: false,
    toppings: false,
    brunch: true,
    takeaway: true,
  },
  siteOverrides: {
    brand: {
      name: "MAISON TABLE",
      shortName: "Maison",
      descriptor: "Event Hospitality & Private Dining",
      tagline: "Puesta en escena gastronómica y servicio exclusivo",
      description: "Catering de alta gama para jornadas corporativas, lanzamientos de marca y cenas privadas.",
      logo: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=120&q=80",
    },
    features: { delivery: true, pickup: true, tableOrders: false, waiterCall: false, reservation: true, ordering: true, story: true },
    content: {
      hero: {
        eyebrow: "Private Dining & Event Architecture",
        titlePrefix: "Diseñamos",
        titleAccent: "el encuentro.",
        subtitle: "Servicio gastronómico a medida para jornadas corporativas, recepciones cocktail y celebraciones privadas.",
        cta: "Consultar Propuesta",
        ctaHref: "menu",
        image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1920&q=85",
      },
      story: {
        eyebrow: "Hospitality & Puesta en Escena",
        watermark: "TABLE",
        titlePrefix: "Cada detalle",
        titleAccent: "importa.",
        sectionTag: "Cuaderno de Experiencias",
        primaryDescription: "No nos limitamos a servir comida. Diseñamos la vajilla, la iluminación y los tiempos de servicio para acompañar el ritmo del encuentro.",
        secondaryDescription: "Trabajamos estaciones en vivo y bandejas de pase sincronizadas para que los invitados interactúen con libertad.",
        backgroundImage: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1800&q=85",
        labels: { traceability: "Detalle del Evento", closeSheet: "Cerrar Ficha" },
        archive: [
          {
            titulo: "Desayuno de Negocios",
            subtitulo: "Morning Setup",
            nota: "Estaciones de café de especialidad, jugos prensados en frío y bollería fina montados previo al inicio.",
            origen: "Corporate Service",
            src: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=1200&q=85",
          },
          {
            titulo: "Live Pasta Station",
            subtitulo: "Cocina a la Vista",
            nota: "Chefs finalizando platos de pasta al momento para aportar dinamismo y aroma al salón.",
            origen: "Live Cook",
            src: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=1200&q=85",
          },
          {
            titulo: "Cocktail Reception",
            subtitulo: "Pase de Bandejas",
            nota: "Bocados fríos y calientes diseñados en tamaño justo para comer de pie en un solo bocado.",
            origen: "Cocktail Pass",
            src: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=85",
          },
          {
            titulo: "Mesa Imperial",
            subtitulo: "Vajilla & Cristal",
            nota: "Cristalería pulida, lino natural y menú por pasos para comidas privadas.",
            origen: "Private Dining",
            src: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=85",
          },
        ],
      },
      ctaTransition: {
        eyebrow: "Cotización a Medida",
        titlePrefix: "Creemos tu próxima",
        titleAccent: "celebración.",
        description: "Contanos la fecha, cantidad de invitados y formato del evento para preparar un presupuesto personalizado.",
        buttonText: "Solicitar Propuesta",
      },
      footer: {
        backgroundImage: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1920&q=85",
        description: "Maison Table · Event Hospitality & Private Dining Architecture",
        credits: "Gastro Engine Core",
      },
    },
  },
  menu: { categories: cateringCategories, products: cateringProducts },
};